site_name: DEwithManish
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli
site_url: https://manishchetpalli.github.io/

repo_url: https://github.com/manishchetpalli/DataEngineeringNotes
repo_name: "AnalyticsWithManish"
edit_uri: edit/main/docs/


copyright: >
  Copyright &copy; 2026 Manishkumar Chetpalli. 
  This website is maintained for personal learning and documentation purposes.
  Content is inspired by various public resources and original authors.


theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  favicon: assets/images/sqldeveloper-original.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.instant
    - search.highlight
    - search.suggest
    - search.share
    - navigation.footer  
    - content.action.feedback 
    - toc.follow
    
    
  palette:
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Projects/Setup:
    - Flink Ignite Custom Dialect: projects/flink-ignite.md
    - FastAPI Kafka Producer: projects/kafkaapi.md
    - Airflow Setup: tooling/airflow_install_onpremise.md
    - Ignite Multi Node Setup: tooling/igniteinstall.md
    - Kafka Multi Node Setup: tooling/kafka_install_zookeeper.md
    - Kubernetes Setup: tooling/kubernetes_install.md
    - Sparkstandalone Multi Node: tooling/spark3standalone.md
    - Spark on Kubernetes: tooling/sparkkube.md
    - Flink on Kubernetes: tooling/flinkonk8.md
    - Multiple Spark version on YARN: tooling/spark23yarn.md
  - Fundamentals:
      - Overview: DataEngineering/DE.md
      - DE Lifecycle: DataEngineering/DEcycle.md
      - DE UnderCurrents: DataEngineering/DEundercurrent.md
      - DE Architecture & Design: DataEngineering/DesigningGDA.md
      - Data Orchestration: airflow/dataorchestration.md
      - Data Warehousing: datawarehousing/overview.md
      - File Formats: DataEngineering/fileformat.md
      - Kerberos: hadoop/kerberos.md
  - Big Data: 
    - Apache Hadoop: hadoop/HDFS.md
    - Apache MapReduce: hadoop/mapreduce.md
    - Apache Yarn: hadoop/yarn.md
    - Apache Hive: hive/overview.md
    - Apache Airflow: airflow/airflow.md 
    - Apache Spark: spark/intro.md
    - Apache Kafka: kafka/overview.md
    - Apache Flink: flink/flink.md
    - Apache Ignite: ignite/ignite.md
    - Apache Iceberg: iceberg/iceberg.md
  - Cloud computing:
    - AWS: cloud/aws.md
    - Databricks: cloud/databricks.md
  - About Me: about.md
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manishkumarchetpalli/
    - icon: fontawesome/brands/github
      link: https://github.com/manish-chet
  footer: |
    ⚠️ Content is written for personal learning purposes based on various public resources.

extra_css:
  - stylesheets/extra.css